Class {
	#name : #BCRADataReaderTest,
	#superclass : #TestCase,
	#category : #'YavuInformes-Test'
}

{ #category : #'as yet unclassified' }
BCRADataReaderTest >> fvBCRATestStream [

	^ ReadStream on: '

<script language="JavaScript">
<!--
  javascript:window.history.forward(0);
//-->
</script>

<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Informes por CUIT</title>

<meta http-equiv="Expires" CONTENT="0">
<meta http-equiv="Cache-Control" CONTENT="no-cache">
<meta http-equiv="Pragma" CONTENT="no-cache">

<link rel="stylesheet" type="text/css" href="../comunes/contenido.css">

</head> 

<body bgcolor="#FFFFFF" onLoad="if(history.length>0)history.go(+1)">

<div id="Imprimir"style="position:absolute; left:439px; top:12px; width:22px; height:22px; z-index:18">
<input type="image" value="Imprimir" onClick="window.print()" name="impresion" src="../images/iconos/icoimprimir.gif" width="22" height="22">
</div>


<div id="Pregunta" style="position:absolute; left:529px; top:12px; width:24; height:20px; z-index:2">
<a title="Aclaraciones de Deudores del Sistema Financiero" target="_blank" href="cr010100.asp">
<img src="../images/iconos/icoyuda.gif" border="0"></a></div>

<div id="Layer1" style="position:absolute; left:15px; top:15px; width:570px; height:25px; z-index:1">
	<p align="center"><img src="../images/titulos/titconsultacuit.jpg" width="570" height="25">

</div>





<div id="Layer4" align="center" style="position:absolute; left:15; top:83; width:570;">




<table border="1" width="100%" id="table3">
	<tr>
		<td style="text-align: center">
			<a title="Nueva Consulta por CUIT" target="_self" href="cr010000.asp?primera_vez=0">
			<img src="../images/botones/btnnuevaconsulta.jpg" border="0"></a>
		</td>
	</tr>

	<tr>
		<td class="Celda_Vacia_Titulo" height="21">
			<b>Consulta de información para el CUIT-CUIL-CDI 23276349759</b>
		</td>
	</tr>
	
	<tr>
		<td class="Celda_Vacia_Titulo"><b> </b>
		</td>
	</tr>
 


	<tr>
		<td style="text-align: center"><font color="#003366">
		<span style="font-size: 7pt; font-weight: 700; text-decoration: underline">CENTRAL DE DEUDORES DEL SISTEMA FINANCIERO</span></font></td>
	</tr>


	<tr>
		<td style="text-align: center">&nbsp;
		</td>
	</tr>
	<tr>
		<td style="text-align: center">
		   La magnitud del monto de deuda se encuentra expresada en "miles de pesos con un decimal".
		</td>
	</tr>
</table>



<table border="1" cellpadding="0" cellspacing="1" width="571px" id="table1" class="Tabla_Borde">
	<tr>
		<td class="Celda_Borde_Titulo">DENOMINACION DEL DEUDOR</td>
		<td class="Celda_Borde_Titulo">ENTIDAD</td>
		<td class="Celda_Borde_Titulo">PERIODO</td>
		<td class="Celda_Borde_Titulo">SITUACION</td>
		<td class="Celda_Borde_Titulo">MONTO</td>
		<td class="Celda_Borde_Titulo">DIAS <br> ATRASO</td>
		<td class="Celda_Borde_Titulo">OBSERVACIONES</td>		

	</tr>



	<tr>
		<td class="Celda_Borde_Izquierda">VOZZI FACUNDO</td>
		<td class="Celda_Borde_Izquierda">BANCO DE LA NACION ARGENTINA                                                    </td>
		<td class="Celda_Borde_Centro">06/13</td>
		<td class="Celda_Borde_Centro"><font color="#008000">1</font></td>
		<td class="Celda_Borde_Centro">102,6</td>
		<td class="Celda_Borde_Centro">N/A</td>
		<td class="Celda_Borde_Centro">
         
		   -
			
		

		</td>
	</tr>





	<tr>
		<td class="Celda_Borde_Izquierda">VOZZI FACUNDO</td>
		<td class="Celda_Borde_Izquierda">BBVA BANCO FRANCES S.A.                                                         </td>
		<td class="Celda_Borde_Centro">06/13</td>
		<td class="Celda_Borde_Centro"><font color="#008000">1</font></td>
		<td class="Celda_Borde_Centro">5,6</td>
		<td class="Celda_Borde_Centro">N/A</td>
		<td class="Celda_Borde_Centro">
         
		   -
			
		

		</td>
	</tr>


  
	</table>
	
<table border="1" width="100%" id="table1" cellpadding="0" cellspacing="0">


	<tr>
		<td>&nbsp;
		</td>
	</tr>
	<tr>
		<td>
		<p style="text-align: left">Ante cualquier duda o error en la información, se señala que los 
		derechos de rectificación, actualización, supresión, confidencialidad, 
		deben ejercerse ante las entidades cedentes que sean parte en la 
		relación jurídica a que se refiere.<br>
		<br>
		<b>
		<font size="7" color="#003366" style="font-size: 7pt; text-decoration: underline">
		<a target="_blank" href="http://www.bcra.gob.ar/sisfin/sf010000.asp">Consulte aquí más información de las entidades.</a></font></b></p>
		<p style="text-align: left">
		<b>
		<font size="7" color="#003366" style="font-size: 7pt; text-decoration: underline">
		<a target="_blank" href="cr010100.asp">Aclaraciones relacionadas con los 
		datos de esta pantalla.</a></font></b><br>
		</p>
		<p>&nbsp;<br>
		A solicitud de cada cliente, dentro de los 10 días corridos del pedido, 
		la entidad deberá comunicarle la última clasificación que le ha 
		asignado, junto con los fundamentos que la justifican según la 
		evaluación realizada por la entidad y las clasificaciones asignadas que 
		surjan de la última información disponible en la &quot;Central de deudores 
		del sistema financiero&quot;.<br>
		<br>
		Las financiaciones comprenden la asistencia crediticia, participaciones en otras sociedades, garantías otorgadas y responsabilidades eventuales, según las Normas 
de Procedimiento del régimen informativo de Deudores del Sistema Financiero. Se aclara que los deudores con préstamos 
hipotecarios pueden tener asignado además de esos préstamos, las garantías otorgadas por los bancos minoristas. 
		</td>
	</tr>


</table>


<table border="1" width="100%" id="table1" cellpadding="0" cellspacing="0">
	<tr>
		<td>&nbsp;
		</td>
	</tr>
	<tr>
		<td>
<p style="text-align: center"><font color="#003366">
<span style="font-size: 7pt; font-weight: 700; text-decoration: underline">CENTRAL DE DEUDORES DE ENTIDADES LIQUIDADAS</span></font></td>
	</tr>
	<tr>
		<td>&nbsp;
</td>
	</tr>
	<tr>
		<td>
No existen registros informados con clave de identificación fiscal por entidades liquidadas por el Banco Central con anterioridad al 22.10.92, excepto que el deudor haya sido informado con número de documento de identidad. El archivo completo puede consultarse accediendo al 
DVD que mensualmente difunde la Gerencia de Liquidación de Entidades del BCRA.
		</td>
	</tr>
</table>

<table border="1" width="100%" id="table1" cellpadding="0" cellspacing="0">
	<tr>
		<td>&nbsp;
		</td>
	</tr>
	<tr>
		<td>
<p style="text-align: center"><font color="#003366">
<span style="font-size: 7pt; font-weight: 700; text-decoration: underline">DEUDORES EN SITUACIÓN IRREGULAR DE EX ENTIDADES FINANCIERAS</span></font>  </td>
	</tr>
	<tr>
		<td>&nbsp;
</td>
	</tr>
	<tr>
		<td>
No existen registros informados con clave de identificación fiscal por entes residuales de entidades financieras públicas privatizadas o en proceso de privatización o disolución, entidades financieras cuya autorización para funcionar haya sido revocada por el Banco Central y se encuentren en estado de liquidación judicial o quiebra, o fideicomisos en los que SEDESA sea beneficiario, excepto que haya sido informado con número de documento de identidad. El archivo completo puede consultarse accediendo al DVD "Central de deudores del sistema financiero" de frecuencia mensual que difunde la Gerencia de Gestión de la Información del BCRA.
		</td>
	</tr>
		<tr>
		<td>&nbsp;
		</td>
	</tr>
	</tr>
	

</table>

<br>

<table border="1" width="100%" id="table1" cellpadding="0" cellspacing="0">
	
	<tr>
		<td>
		<p style="text-align: center"><font color="#003366">
		<span style="font-size: 7pt; font-weight: 700; text-decoration: underline">CENTRAL DE CHEQUES RECHAZADOS</span></font></td>
	</tr>	
	
</table>
<br>



<br>&nbsp;



<table border="1" id="table1" class="Tabla_Borde" cellpadding="0" cellspacing="1">
	<tr>
		<td class="Celda_Borde_Titulo">
			No Existen Registraciones de Cheques rechazados para esta Consulta
		</td>
	</tr>
</table>

<br>&nbsp;
<table border="1" width="100%" id="table3">
	<tr>
		<td>
			Estas consultas se realizan sobre la Central de cheques rechazados, conformada por datos recibidos de los bancos que se publican sin
			alteraciones de acuerdo con los plazos dispuestos en el artículo 26, inciso 4. de la Ley 25.326 de Protección de los Datos Personales y con el criterio establecido en la Comunicación "B" 7074 y 8103. Su difusión no implica conformidad por parte de este Banco Central.
		</td>
	</tr>
	
	
		<tr>
		<td class="Celda_Vacia_Titulo">&nbsp;
</td>
	</tr>

	
		<tr>
		<td class="Celda_Vacia_Titulo">        <u>ACCESO A CONSULTA DE DEUDAS POR IMPUESTOS PROVINCIALES
&nbsp;</u></td>
	</tr>

	
		<tr>
		<td class="Celda_Vacia_Titulo">
<p style="text-align: center">Acceso a consultas de deudas de ARBA.
		</td>
	</tr>

	<tr>
		<td>&nbsp;
		</td>
	</tr>	
	<tr>
		<td>
La información referida en el vínculo al que se accede a continuación corresponde a ARBA (Agencia de Recaudación de la Provincia de Buenos Aires), no teniendo este BCRA ninguna responsabilidad por los datos allí contenidos.&nbsp;
		</td>
	</tr>
	<tr>
		<td>&nbsp;
		</td>
	</tr>		
	<tr>
		<td>

		<p style="text-align: center">
		
		
		</td>
	</tr>
	
<tr>
		<td>
		<p style="text-align: center"><span class="Fuente_Color">
		<span style="font-size: 7pt; font-weight: 700">Acceso a consultas de 
		deudas de&nbsp;Rentas Córdoba.</span></span></td>
	</tr>	


	<tr>
		<td>&nbsp;</td>
	</tr>	
	<tr>
		<td>La información referida en el vínculo al que se accede a continuación corresponde a 
		Rentas Córdoba, no teniendo este BCRA ninguna responsabilidad por los 
		datos allí contenidos.</td>
	</tr>	


	<tr>
		<td>&nbsp;</td>
	</tr>	
	<tr>
		<td>
		<p style="text-align: center">&nbsp;
		</td>
	</tr>	
	
	<tr>
		<td>
		<p style="text-align: center"><span class="Fuente_Color">
		<span style="font-size: 7pt; font-weight: 700">Acceso a consultas de 
		deudas de&nbsp;Rentas de Rio Negro.</span></span></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>La información referida en el vínculo al que se accede a continuación corresponde a 
		Rentas de Rio Negro, no teniendo este BCRA ninguna responsabilidad por los 
		datos allí contenidos.</td>
	</tr>
	
	<tr>
		<td style="text-align: center">
		</td>
	</tr>
		<tr>
		<td>
		<p style="text-align: center"><span class="Fuente_Color">
		<span style="font-size: 7pt; font-weight: 700">Acceso a consultas de 
		deudas de&nbsp;Rentas de Corrientes.</span></span></td>
	</tr>
		<tr>
		<td>&nbsp;</td>
	</tr>
	
	<tr>
		<td>La información referida en el vínculo al que se accede a continuación corresponde a 
		Rentas de Corrientes, no teniendo este BCRA ninguna responsabilidad por los 
		datos allí contenidos.</td>
	</tr>
	
	<tr>
		<td style="text-align: center">
		</td>
	</tr>	
	
	
			<tr>
		<td>
		<p style="text-align: center"><span class="Fuente_Color">
		<span style="font-size: 7pt; font-weight: 700">Acceso a consultas de 
		deudas de&nbsp;Rentas de Salta.</span></span></td>
	</tr>
		<tr>
		<td>&nbsp;</td>
	</tr>
	
	<tr>
		<td>La información referida en el vínculo al que se accede a continuación corresponde a 
		Rentas de Salta, no teniendo este BCRA ninguna responsabilidad por los 
		datos allí contenidos.</td>
	</tr>
	
	<tr>
		<td style="text-align: center">
		</td>
	</tr>
	
	<tr>
		<td style="text-align: center">
			<a title="Nueva Consulta por CUIT" target="_self" href="cr010000.asp">
			<img src="../images/botones/btnnuevaconsulta.jpg" border="0"></a>
		</td>
	</tr>
</table>


</div>	







</body>
</html>
'

]

{ #category : #'as yet unclassified' }
BCRADataReaderTest >> fvPerson [
	
	^NaturalPerson nombre: 'Facundo Vozzi' dni: '27634975' sexo: 'M'
]

{ #category : #'as yet unclassified' }
BCRADataReaderTest >> test1 [

	| bcraDataReader |
	
	bcraDataReader := (BCRADataReader on: self fvPerson) htmlBasicStream: self fvBCRATestStream.
	bcraDataReader parseHtmlData.
	self assert: bcraDataReader basicData  hasDebtElements.
	self assert: bcraDataReader basicData debtElementsCount = 3.
	self assert: (bcraDataReader basicData existsDebtFor: 'VOZZI FACUNDO') notNil
	

]
